x-apiservice-env: &apiservice-env
    ASPNETCORE_ENVIRONMENT: Development
    DOTNET_USE_POLLING_FILE_WATCHER: "1"
    ASPNETCORE_URLS: "http://+:80;https://+:443"
    DOTNET_RUNNING_IN_CONTAINER: "true"
    DOTNET_SYSTEM_GLOBALIZATION_INVARIANT: "false"
    NUGET_XMLDOC_MODE: skip
    ASPNETCORE_Kestrel__Certificates__Default__Path: /https/aspnetapp.pfx
    ASPNETCORE_Kestrel__Certificates__Default__Password: ${CERTIFICATE_PASSWORD}
    AWS__LocalStack__ServiceURL: http://localstack:4566
    AWS__UseLocalStack: true
    AWS__Region: us-east-1
    AWS__Profile: default
    Services__CatalogServiceBaseUrl: "http://geminicatalog:80"
    Services__CustomerServiceBaseUrl: "http://geminicustomer:80"
    Services__InventoryServiceBaseUrl: "http://geminiinventory:80"

services:
    catalog:
        container_name: geminicatalog
        image: itshubert/geminicatalog
        environment:
            <<: *apiservice-env
            ConnectionStrings__GeminiCatalogDbContext: ${GeminiCatalogDbContext}
        networks:
            - app-network
        ports:
            - "4000:80"
            - "4001:443"
        volumes:
            - ~/.aspnet/https:/https:ro

    customer:
        container_name: geminicustomer
        image: itshubert/geminicustomer
        environment:
            <<: *apiservice-env
            ConnectionStrings__GeminiCustomerDbContext: ${GeminiCustomerDbContext}
        networks:
            - app-network
        ports:
            - "4004:80"
            - "4005:443"
        volumes:
            - ~/.aspnet/https:/https:ro

    inventory:
        container_name: geminiinventory
        image: itshubert/geminiinventory
        # entrypoint: /bin/bash
        # stdin_open: true
        # tty: true
        environment:
            <<: *apiservice-env
            ConnectionStrings__GeminiInventoryDbContext: ${GeminiInventoryDbContext}
            QueueSettings__OrderSubmitted: "http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/order-submitted-inventory.fifo"
        networks:
            - app-network
        ports:
            - "4006:80"
            - "4007:443"
        volumes:
            - ~/.aspnet/https:/https:ro

    order:
        container_name: geminiorder
        image: itshubert/geminiorder
        environment:
            <<: *apiservice-env
            ConnectionStrings__GeminiOrderDbContext: ${GeminiOrderDbContext}
            QueueSettings__InventoryReserved: "http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/inventory-reserved-order.fifo"
            QueueSettings__OrderStockFailed: "http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/order-stock-failed-order.fifo"
            Queue_Settings__OrderShipped: "http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/fulfillment-ordershipped-order.fifo"
        networks:
            - app-network
        ports:
            - "4002:80"
            - "4003:443"
        volumes:
            - ~/.aspnet/https:/https:ro

    orderfulfillment:
        container_name: geminiorderfulfillment
        image: itshubert/geminiorderfulfillment
        environment:
            <<: *apiservice-env
            ConnectionStrings__GeminiOrderFulfillmentDbContext: ${GeminiOrderFulfillmentDbContext}
            QueueSettings__InventoryReserved: "http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/inventory-reserved-fulfillment.fifo"
            QueueSettings__OrderSubmitted: "http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/order-submitted-fulfillment.fifo"
            QueueSettings__JobInProgress: "http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/job-pickinprogress-order.fifo"
            QueueSettings__ShippingLabelGenerated: "http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/shipping-labelgenerated-fulfillment.fifo"
        networks:
            - app-network
        ports:
            - "4008:80"
        volumes:
            - ~/.aspnet/https:/https:ro

    warehouse:
        container_name: geminiwarehouse
        image: itshubert/geminiwarehouse
        environment:
            <<: *apiservice-env
            ConnectionStrings__GeminiWarehouseDbContext: ${GeminiWarehouseDbContext}
            QueueSettings__FulfillmentTaskCreated: "http://sqs.us-east-1.localhost.localstack.cloud:4566/000000000000/fulfillment-task-created-warehouse.fifo"
        networks:
            - app-network
        ports:
            - "4009:80"
        volumes:
            - ~/.aspnet/https:/https:ro

networks:
    app-network:
        driver: bridge
        external: true
